### ISSUE TITLE
PA inbox notification results in incorrect sort

### ISSUE THREAD

**Issue by railworks2** [roblox-dev-forum/post-approval#24]
## Description of bug
When clicking the X messages in Post_Approval inbox notification, the order in which the inbox is shown is not to the preference of the end user, in my case oldest to newest.

## Reproduction Steps

1. Go to preferences -> Interface -> Ensure Sort post approval inbox from oldest to newest is ticked
![image](https://user-images.githubusercontent.com/27024242/81713856-51541600-946e-11ea-991c-b142fce76247.png)
2. Find the "[X] messages in Post Approval" notification, an example of this is
![image](https://user-images.githubusercontent.com/27024242/81713355-ac393d80-946d-11ea-9ca1-726879c21e63.png)
3. Click the notification
4. Observe the sort of the inbox
5. Click the Post_Approval inbox button
![image](https://user-images.githubusercontent.com/27024242/81715068-ac3a3d00-946f-11ea-8287-1030a4f4a9e4.png)
6.  Observe the sort of the inbox now

## Expected Results
Same sorting as preferences (Oldest to Newest) across the board

## Actual Results
Sorting is the default (Newest to Oldest) when clicking that notification

-----

## Notes

The URL after that notification was https://devforum.roblox.com/u/railworks2/messages/group/post_approval
While the Post Approval inbox button URL resulted in https://devforum.roblox.com/u/railworks2/messages/group/Post_Approval

**Comment by buildthomas** [comment]
Solved by #25
